@url = https://8080-kauakyoto-games1110-n4jnkxnlhxq.ws-us116.gitpod.io

GET  {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Vampire Survivors",
    "plataformas": [
        {"id": 1},
        {"id": 2}
    ]
}

###
DELETE {{url}}/jogos/2

###
PUT {{url}}/jogos/1
Content-Type: application/json

{
    "titulo": "Vampire Survivors - Alterado",
    "plataformas": [
        {"id": 1}
    ]
}