@url = https://8080-kauakyoto-games1110-ez4pa9kb1y7.ws-us116.gitpod.io
GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "XBox"
}

###
GET {{url}}/plataformas/8