@url = https://8080-kauakyoto-games1110-n4jnkxnlhxq.ws-us116.gitpod.io
GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "PC"
}

###
GET {{url}}/plataformas/8